import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css";

// Set up the font with a CSS variable
const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque", // you can also rename it if you want
  subsets: ["latin"],
  display: "swap", // optional but good for performance
});

export const metadata: Metadata = {
  title: "Avatar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${bricolageGrotesque.variable}`}>
      <body className="antialiased font-bricolage">{children}</body>
    </html>
  );
}
